hls-main/force-app/main/default/objects/Application_Access_Request__c/Application_Access_Request__c.object-meta.xml
<CustomObject>
    <label>Application Access Request</label>
    <nameField>
        <displayFormat>Req {0}</displayFormat>
        <label>Application Access Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Access Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hls-main/force-app/main/default/objects/Application_Access_Request__c/fields/Application_Description__c.field-meta.xml
<CustomField>
    <fullName>Application_Description__c</fullName>
    <description>Application Description</description>
    <label>Application Description</label>
    <length>250</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

hls-main/force-app/main/default/objects/Application_Access_Request__c/fields/Application_Name__c.field-meta.xml
<CustomField>
    <fullName>Application_Name__c</fullName>
    <description>What members see as name of application</description>
    <inlineHelpText>What members see as name of application</inlineHelpText>
    <label>Application Name</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

hls-main/force-app/main/default/objects/Application_Access_Request__c/fields/Application_privacy_policy__c.field-meta.xml
<CustomField>
    <fullName>Application_privacy_policy__c</fullName>
    <description>Does your application have a privacy policy?</description>
    <inlineHelpText>Does your application have a privacy policy?</inlineHelpText>
    <label>Application have privacy policy?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

hls-main/force-app/main/default/objects/Application_Access_Request__c/fields/Application_Redirect_URL_s__c.field-meta.xml
<CustomField>
    <fullName>Application_Redirect_URL_s__c</fullName>
    <description>Where OIDC requests are redirected (Comma-delimited).</description>
    <inlineHelpText>Where OIDC requests are redirected (Comma-delimited).</inlineHelpText>
    <label>Application Redirect URL(s)</label>
    <length>1500</length>
    <type>LongTextArea</type>
</CustomField>

hls-main/force-app/main/default/objects/Application_Access_Request__c/fields/Application_Release_Date__c.field-meta.xml
<CustomField>
    <fullName>Application_Release_Date__c</fullName>
    <description>When do you plan to publish your application for public use?</description>
    <inlineHelpText>When do you plan to publish your application for public use?</inlineHelpText>
    <label>Application Release Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

hls-main/force-app/main/default/objects/Application_Access_Request__c/fields/Captures_user_device_data__c.field-meta.xml
<CustomField>
    <fullName>Captures_user_device_data__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Does your Privacy Policy state if the Application captures any of the user&apos;s device data?</description>
    <inlineHelpText>Does your Privacy Policy state if the Application captures any of the user&apos;s device data?</inlineHelpText>
    <label>Captures user device data?</label>
    <type>Checkbox</type>
</CustomField>

hls-main/force-app/main/default/objects/Application_Access_Request__c/fields/Company_Address__c.field-meta.xml
<CustomField>
    <fullName>Company_Address__c</fullName>
    <label>Company Address</label>
    <length>150</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

hls-main/force-app/main/default/objects/Application_Access_Request__c/fields/Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Company_Name__c</fullName>
    <description>What members see as name of company.</description>
    <inlineHelpText>What members see as name of company.</inlineHelpText>
    <label>Company Name</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

hls-main/force-app/main/default/objects/Application_Access_Request__c/fields/Company_Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Company_Primary_Contact__c</fullName>
    <description>Person oversees attestation of App security, can be contacted for for delisting/violations of terms and services, or change developer contact info.</description>
    <inlineHelpText>Person oversees attestation of App security, can be contacted for for delisting/violations of terms and services, or change developer contact info.</inlineHelpText>
    <label>Company Primary Contact</label>
    <length>150</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

hls-main/force-app/main/default/objects/Application_Access_Request__c/fields/Company_Primary_Contact_Email__c.field-meta.xml
<CustomField>
    <fullName>Company_Primary_Contact_Email__c</fullName>
    <description>Person oversees attestation of App security, can be contacts for delisting/violations of terms and services, or change developer contact info.</description>
    <inlineHelpText>Person oversees attestation of App security, can be contacts for delisting/violations of terms and services, or change developer contact info.</inlineHelpText>
    <label>Company Primary Contact Email</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

hls-main/force-app/main/default/objects/Application_Access_Request__c/fields/Company_URL__c.field-meta.xml
<CustomField>
    <fullName>Company_URL__c</fullName>
    <label>Company URL</label>
    <length>150</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

hls-main/force-app/main/default/objects/Application_Access_Request__c/fields/Developer_Contact_Email__c.field-meta.xml
<CustomField>
    <fullName>Developer_Contact_Email__c</fullName>
    <description>Person can authorize change of App Tokens, return URLs, etc.</description>
    <inlineHelpText>Person can authorize change of App Tokens, return URLs, etc.</inlineHelpText>
    <label>Developer Contact Email</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

hls-main/force-app/main/default/objects/Application_Access_Request__c/fields/Developer_Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Developer_Contact_Name__c</fullName>
    <label>Developer Contact Name</label>
    <length>150</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

hls-main/force-app/main/default/objects/Application_Access_Request__c/fields/Enter_the_URL_for_your_privacy_policy__c.field-meta.xml
<CustomField>
    <fullName>Enter_the_URL_for_your_privacy_policy__c</fullName>
    <label>Enter the URL for your privacy policy</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

hls-main/force-app/main/default/objects/Application_Access_Request__c/fields/Informs_user_of_data_access__c.field-meta.xml
<CustomField>
    <fullName>Informs_user_of_data_access__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Does your Privacy Policy inform the user how their data (i.e. PHI) will be accessed, exchanged, or used by another entity (including in the future)?</description>
    <inlineHelpText>Does your Privacy Policy inform the user how their data (i.e. PHI) will be accessed, exchanged, or used by another entity (including in the future)?</inlineHelpText>
    <label>Informs user of data access?</label>
    <type>Checkbox</type>
</CustomField>

hls-main/force-app/main/default/objects/Application_Access_Request__c/fields/Instructions_to_dispose_health_data__c.field-meta.xml
<CustomField>
    <fullName>Instructions_to_dispose_health_data__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Do you publicly host a link with instructions for how a user can request to securely and completely dispose of their identifiable health data?</description>
    <inlineHelpText>Do you publicly host a link with instructions for how a user can request to securely and completely dispose of their identifiable health data?</inlineHelpText>
    <label>Instructions to dispose health data?</label>
    <type>Checkbox</type>
</CustomField>

hls-main/force-app/main/default/objects/Application_Access_Request__c/fields/Require_acknowledgement__c.field-meta.xml
<CustomField>
    <fullName>Require_acknowledgement__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Does your application require the user to acknowledge your privacy policy before authorization?</description>
    <inlineHelpText>Does your application require the user to acknowledge your privacy policy before authorization?</inlineHelpText>
    <label>Require acknowledgement?</label>
    <type>Checkbox</type>
</CustomField>

hls-main/force-app/main/default/objects/Application_Access_Request__c/fields/Requires_express_consent__c.field-meta.xml
<CustomField>
    <fullName>Requires_express_consent__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Does your Privacy Policy require express consent from a user/patient before the patient&apos;s health information is accessed, exchanged, or used, including receiving express consent before a patient&apos;s health information is shared or sold (other than disclosures required by law or disclosures necessary in connection with the sale of the application or a similar transaction)?</description>
    <inlineHelpText>Does your Privacy Policy require express consent from a user/patient before the patient&apos;s health information is accessed, exchanged, or used, including receiving express consent before a patient&apos;s health information is shared or sold (other than disclosures required by law or disclosures necessary in connection with the sale of the application or a similar transaction)?</inlineHelpText>
    <label>Requires express consent?</label>
    <type>Checkbox</type>
</CustomField>

hls-main/force-app/main/default/objects/Application_Access_Request__c/fields/Select_APIs__c.field-meta.xml
<CustomField>
    <fullName>Select_APIs__c</fullName>
    <label>Select APIs</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Provider Directory API</fullName>
            </value>
            <value>
                <fullName>Patient Access API</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

hls-main/force-app/main/default/objects/Application_Access_Request__c/fields/SH_Dev_Support_Email_Label__c.field-meta.xml
<CustomField>
    <fullName>SH_Dev_Support_Email_Label__c</fullName>
    <label>SH-Dev-Support-Email_Label</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

hls-main/force-app/main/default/objects/Application_Access_Request__c/fields/SH_Dev_Terms_Of_Use_Link__c.field-meta.xml
<CustomField>
    <fullName>SH_Dev_Terms_Of_Use_Link__c</fullName>
    <description>Need the full Link from Daniel Royer</description>
    <label>SH-Dev-Terms-Of-Use_Link</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

hls-main/force-app/main/default/objects/Application_Access_Request__c/fields/SH_ServiceNow_AssignmentGroup_Label__c.field-meta.xml
<CustomField>
    <fullName>SH_ServiceNow_AssignmentGroup_Label__c</fullName>
    <label>SH-ServiceNow-AssignmentGroup-Label</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

hls-main/force-app/main/default/objects/Application_Access_Request__c/fields/SH_ServiceNow_CI_Label__c.field-meta.xml
<CustomField>
    <fullName>SH_ServiceNow_CI_Label__c</fullName>
    <label>SH-ServiceNow-CI-Label</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

hls-main/force-app/main/default/objects/Application_Access_Request__c/fields/SH_ServiceNow_Email_Label__c.field-meta.xml
<CustomField>
    <fullName>SH_ServiceNow_Email_Label__c</fullName>
    <label>SH-ServiceNow-Email-Label</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

hls-main/force-app/main/default/objects/Application_Access_Request__c/fields/SH_ServiceNow_ShortDesc_Label__c.field-meta.xml
<CustomField>
    <fullName>SH_ServiceNow_ShortDesc_Label__c</fullName>
    <label>SH-ServiceNow-ShortDesc-Label</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

hls-main/force-app/main/default/objects/Application_Access_Request__c/fields/Shows_how_to_terminate_access__c.field-meta.xml
<CustomField>
    <fullName>Shows_how_to_terminate_access__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Does your Privacy Policy state how the user can terminate the Application&apos;s access to user&apos;s data?</description>
    <inlineHelpText>Does your Privacy Policy state how the user can terminate the Application&apos;s access to user&apos;s data?</inlineHelpText>
    <label>Shows how to terminate access?</label>
    <type>Checkbox</type>
</CustomField>

hls-main/force-app/main/default/objects/Application_Access_Request__c/fields/Terms_of_Use__c.field-meta.xml
<CustomField>
    <fullName>Terms_of_Use__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Required before the form can be submitted.</description>
    <inlineHelpText>Required before the form can be submitted.</inlineHelpText>
    <label>Do you agree to our Terms of Use?</label>
    <type>Checkbox</type>
</CustomField>

hls-main/force-app/main/default/objects/Application_Access_Request__c/fields/User_data_will_be_shared__c.field-meta.xml
<CustomField>
    <fullName>User_data_will_be_shared__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Does your Privacy Policy state if the user&apos;s data will be shared or sold (at any time)?</description>
    <inlineHelpText>Does your Privacy Policy state if the user&apos;s data will be shared or sold (at any time)?</inlineHelpText>
    <label>User data will be shared?</label>
    <type>Checkbox</type>
</CustomField>

hls-main/force-app/main/default/classes/ApplicationAccessRequestControllerTest.cls
@IsTest
public class ApplicationAccessRequestControllerTest {
    @IsTest
    static void getAPIOptionsTest(){
        acm_pkg__CommunityApi__c communityAPIRec = new acm_pkg__CommunityApi__c();
        communityAPIRec.acm_pkg__ApiId__c = 'testCommunityAPI';
        communityAPIRec.acm_pkg__AssetVersion__c = '1';
        communityAPIRec.acm_pkg__VersionGroup__c = 'testVersion';
        communityAPIRec.acm_pkg__Visibility__c = 'Public';
        communityAPIRec.acm_pkg__Name__c = 'testCommunityAPI';
        communityAPIRec.acm_pkg__AssetType__c = 'api-group';
        insert communityAPIRec;
            
        Test.startTest();
        List<Map<String, String>> apiOptions = ApplicationAccessRequestController.getAPIOptions();
        Test.stopTest();
        
        System.assertNotEquals(apiOptions, null);
    }
    
    @IsTest
    static void getFieldLabelsTest(){
        Test.startTest();
        Map<String, String> fieldLabelMap = ApplicationAccessRequestController.getFieldLabels();
        Test.stopTest();
        
        System.assertNotEquals(fieldLabelMap, null);
    }
    
    @IsTest
    static void saveApplicationAccessRequestTest(){
        Application_Access_Request__c applicationAccessRequestRec = new Application_Access_Request__c();
        applicationAccessRequestRec.Select_APIs__c = 'Patient Access API';
        applicationAccessRequestRec.Application_Name__c = 'SelectHealth Application';
        applicationAccessRequestRec.Application_Description__c = 'Sample Description';
        applicationAccessRequestRec.Application_Release_Date__c = System.today();
        applicationAccessRequestRec.Developer_Contact_Name__c = 'Developer Name';
        applicationAccessRequestRec.Developer_Contact_Email__c = 'developer.name@email.com';
        applicationAccessRequestRec.Company_Name__c = 'SelectHealth';
        applicationAccessRequestRec.Company_URL__c = 'https://selecthealth.org';
        applicationAccessRequestRec.Company_Address__c = 'Salt Lake, Utah';
        applicationAccessRequestRec.Company_Primary_Contact__c = 'Developer Name';
        applicationAccessRequestRec.Company_Primary_Contact_Email__c = 'developer.name@email.com';
        applicationAccessRequestRec.Application_Redirect_URL_s__c = 'https://selecthealth.org';
        applicationAccessRequestRec.Terms_of_Use__c = true;
        applicationAccessRequestRec.Application_privacy_policy__c = 'Yes';
        applicationAccessRequestRec.Require_acknowledgement__c = true;
        applicationAccessRequestRec.Informs_user_of_data_access__c = true;
        applicationAccessRequestRec.User_data_will_be_shared__c = true;
        applicationAccessRequestRec.Captures_user_device_data__c = true;
        applicationAccessRequestRec.Requires_express_consent__c = true;
        applicationAccessRequestRec.Shows_how_to_terminate_access__c = true;
        applicationAccessRequestRec.Instructions_to_dispose_health_data__c = true;
        applicationAccessRequestRec.Enter_the_URL_for_your_privacy_policy__c = 'https://selecthealth.org';
        applicationAccessRequestRec.SH_Dev_Support_Email_Label__c = 'developer.name@email.com';
        applicationAccessRequestRec.SH_Dev_Terms_Of_Use_Link__c = 'developer.name@email.com';
        applicationAccessRequestRec.SH_ServiceNow_AssignmentGroup_Label__c = 'ServiceNow IT ServiceDesk';
        applicationAccessRequestRec.SH_ServiceNow_CI_Label__c = 'ServiceNow CI';
        applicationAccessRequestRec.SH_ServiceNow_Email_Label__c = 'servicenow@email.com';
        applicationAccessRequestRec.SH_ServiceNow_ShortDesc_Label__c = 'ServiceNow';
                                                    
        Test.startTest();
        Application_Access_Request__c insertedApplicationAccessRequest = ApplicationAccessRequestController.saveApplicationAccessRequest(applicationAccessRequestRec);
        Test.stopTest();
        
        System.assertNotEquals(insertedApplicationAccessRequest.Id, null);
    }
    
    @IsTest
    static void saveApplicationAccessRequestExceptionTest(){
        Application_Access_Request__c applicationAccessRequestRec = new Application_Access_Request__c();
        applicationAccessRequestRec.Application_Name__c = 'SelectHealth Application';
        applicationAccessRequestRec.Application_Description__c = 'Sample Description';
        applicationAccessRequestRec.Application_Release_Date__c = System.today();
        applicationAccessRequestRec.Developer_Contact_Name__c = 'Developer Name';
        applicationAccessRequestRec.Developer_Contact_Email__c = 'developer.name@email.com';
        applicationAccessRequestRec.Company_Name__c = 'SelectHealth';
        applicationAccessRequestRec.Company_URL__c = 'https://selecthealth.org';
        applicationAccessRequestRec.Company_Address__c = 'Salt Lake, Utah';
        applicationAccessRequestRec.Company_Primary_Contact__c = 'Developer Name';
        applicationAccessRequestRec.Company_Primary_Contact_Email__c = 'developer.name@email.com';
        applicationAccessRequestRec.Application_Redirect_URL_s__c = 'https://selecthealth.org';
        applicationAccessRequestRec.Terms_of_Use__c = true;
        applicationAccessRequestRec.Application_privacy_policy__c = 'Yes';
        applicationAccessRequestRec.Require_acknowledgement__c = true;
        applicationAccessRequestRec.Informs_user_of_data_access__c = true;
        applicationAccessRequestRec.User_data_will_be_shared__c = true;
        applicationAccessRequestRec.Captures_user_device_data__c = true;
        applicationAccessRequestRec.Requires_express_consent__c = true;
        applicationAccessRequestRec.Shows_how_to_terminate_access__c = true;
        applicationAccessRequestRec.Instructions_to_dispose_health_data__c = true;
        applicationAccessRequestRec.Enter_the_URL_for_your_privacy_policy__c = 'https://selecthealth.org';
        applicationAccessRequestRec.SH_Dev_Support_Email_Label__c = 'developer.name@email.com';
        applicationAccessRequestRec.SH_Dev_Terms_Of_Use_Link__c = 'developer.name@email.com';
        applicationAccessRequestRec.SH_ServiceNow_AssignmentGroup_Label__c = 'ServiceNow IT ServiceDesk';
        applicationAccessRequestRec.SH_ServiceNow_CI_Label__c = 'ServiceNow CI';
        applicationAccessRequestRec.SH_ServiceNow_Email_Label__c = 'servicenow@email.com';
        applicationAccessRequestRec.SH_ServiceNow_ShortDesc_Label__c = 'ServiceNow';
        
        try {
            Test.startTest();
            Application_Access_Request__c insertedApplicationAccessRequest = ApplicationAccessRequestController.saveApplicationAccessRequest(applicationAccessRequestRec);
            Test.stopTest();
            System.assert(false);
        } catch (Exception e) {
            System.assert(true);
        }
    }
    
    @IsTest
    static void getRequestInfoMapTest(){
        Application_Access_Request__c applicationAccessRequestRec = new Application_Access_Request__c();
        applicationAccessRequestRec.Select_APIs__c = 'Patient Access API';
        applicationAccessRequestRec.Application_Name__c = 'SelectHealth Application';
        applicationAccessRequestRec.Application_Description__c = 'Sample Description';
        applicationAccessRequestRec.Application_Release_Date__c = System.today();
        applicationAccessRequestRec.Developer_Contact_Name__c = 'Developer Name';
        applicationAccessRequestRec.Developer_Contact_Email__c = 'developer.name@email.com';
        applicationAccessRequestRec.Company_Name__c = 'SelectHealth';
        applicationAccessRequestRec.Company_URL__c = 'https://selecthealth.org';
        applicationAccessRequestRec.Company_Address__c = 'Salt Lake, Utah';
        applicationAccessRequestRec.Company_Primary_Contact__c = 'Developer Name';
        applicationAccessRequestRec.Company_Primary_Contact_Email__c = 'developer.name@email.com';
        applicationAccessRequestRec.Application_Redirect_URL_s__c = 'https://selecthealth.org';
        applicationAccessRequestRec.Terms_of_Use__c = true;
        applicationAccessRequestRec.Application_privacy_policy__c = 'Yes';
        applicationAccessRequestRec.Require_acknowledgement__c = true;
        applicationAccessRequestRec.Informs_user_of_data_access__c = true;
        applicationAccessRequestRec.User_data_will_be_shared__c = true;
        applicationAccessRequestRec.Captures_user_device_data__c = true;
        applicationAccessRequestRec.Requires_express_consent__c = true;
        applicationAccessRequestRec.Shows_how_to_terminate_access__c = true;
        applicationAccessRequestRec.Instructions_to_dispose_health_data__c = true;
        applicationAccessRequestRec.Enter_the_URL_for_your_privacy_policy__c = 'https://selecthealth.org';
        applicationAccessRequestRec.SH_Dev_Support_Email_Label__c = 'developer.name@email.com';
        applicationAccessRequestRec.SH_Dev_Terms_Of_Use_Link__c = 'developer.name@email.com';
        applicationAccessRequestRec.SH_ServiceNow_AssignmentGroup_Label__c = 'ServiceNow IT ServiceDesk';
        applicationAccessRequestRec.SH_ServiceNow_CI_Label__c = 'ServiceNow CI';
        applicationAccessRequestRec.SH_ServiceNow_Email_Label__c = 'servicenow@email.com';
        applicationAccessRequestRec.SH_ServiceNow_ShortDesc_Label__c = 'ServiceNow';
                                                    
        Test.startTest();
        Map<String, String> requestInfoMap = ApplicationAccessRequestController.getRequestInfoMap(applicationAccessRequestRec);
        Test.stopTest();
        
        System.assertNotEquals(requestInfoMap, null);
    }
}